language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install --allow-all-external -e .
  - pip install coveralls
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  - nosetests
after_success:
  - coverage combine
  - coveralls
services:
  - rabbitmq
  - redis-server
branches:
  only:
    - master
