language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -e . --use-mirrors"
  - "pip install pexpect==2.4 --use-mirrors"
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
script:
  - python setup.py nosetests
services:
  - rabbitmq
branches:
  only:
    - master
