language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements_test.txt
  - pip install -e .
  - pip install coveralls
before_script:
  - cp test_config_travis.py /tmp/kuyruk_config.py
script:
  - pytest -v --cov=kuyruk tests/
after_success:
  - coverage combine
  - coveralls
services:
  - rabbitmq
branches:
  only:
    - master
