language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -r requirements_test.txt
  - pip install -e .
  - pip install coveralls
script:
  - pytest -v --cov=kuyruk tests/
after_success:
  - coverage combine
  - coveralls
services:
  - rabbitmq
branches:
  only:
    - master
