language: python
python:
  - 2.7
install:
  - pip install -r dev_requirements.txt
  - pip install --allow-all-external -e .
  - pip install coveralls
script:
  - nosetests
after_success:
  - coverage combine
  - coveralls
services:
  - rabbitmq
  - redis-server
branches:
  only:
    - master
