language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r requirements_test.txt
  - pip install --allow-all-external -e .
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package kuyruk --cover-erase
after_success:
  - coverage combine
  - coveralls
services:
  - rabbitmq
  - redis-server
branches:
  only:
    - master
